### ISSUE TITLE
提供的百度网盘的数据集无法解压

### ISSUE THREAD

**Issue by Ken-Con** [wepe/O2O-Coupon-Usage-Forecast#5]
提供的百度网盘的数据集无法解压，解压出错。请问能有解决办法吗？或者重新提供一份，谢谢了。

**Comment by zhongjiajie** [comment]
你好@Ken-Con ，天池大赛官网提供数据集，详情点击 [这里](https://tianchi.aliyun.com/getStart/introduction.htm?raceId=231593)

**Comment by Ken-Con** [comment]
@zhongjiajie 谢谢了
