### ISSUE TITLE
wepon/season one下的coupon feature提取问题

### ISSUE THREAD

**Issue by Wind-Ward** [wepe/O2O-Coupon-Usage-Forecast#8]
按照你的视频中的说法(https://tianchi.aliyun.com/video.htm?spm=5176.100066.0.0.8a30bc8AtOyVq) coupon feature提取的应该是feature window(在代码中的feature3,feature2,feature1中直接提取)，但是在代码中是在label window （代码中的dataset3，dataset2，dataset1）中提取的，请问coupon feature为什么在label window中提取特征？谢谢了！

**Comment by wepe** [comment]
这些是穿越特征，在视频的最后几页有提到．
